services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/factorysaas
      - REDIS_URL=redis://redis:6379
      - USE_MONGO=true
      - ENABLE_JOBS=true
      - WHATSAPP_PROVIDER=mock
      - JWT_SECRET=change-me-in-production
      - JWT_EXPIRES_IN=1d
    depends_on:
      - mongo
      - redis
    ports:
      - "4000:4000"

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
